name: Push to Main

on:
  push:
    branches:
      - github

jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to main
        run: |
          git checkout main
          git merge --no-ff ${{ github.ref }}
          git push origin main

